config/routes.rb
require 'resque/server'

ComicShelf::Application.routes.draw do


  devise_scope :user do
    post '/create_with_store', :to => "spree/user_registrations#create_with_store"
    match '/shop/user/logout', :to => "spree/user_sessions#destroy"
  end

  resources :stores do
    resources :subscriptions do
      post 'update_credit_card'
      get 'edit_credit_card'
    end
    resources :plans, :only => :index
  end

  match '', to: 'stores#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  mount Resque::Server.new, :at => "/resque"
  mount Spree::Core::Engine, :at => '/shop', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/pricing', to: "home#pricing"
  root to: 'home#index'
end

app/views/layouts/_home_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="#">Comic Shop</a>
    <ul class="nav">
      <li class="active"><%= link_to "Pricing", pricing_path %></li>
      <li><a href="#">FAQ</a></li>
      <li><a href="#">About</a></li>
    </ul>
  </div>
</div>  

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="#">Comic Shop</a>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicShelf</title>
  <%= yield :dynamic_javascripts %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV['STRIPE_PUBLIC_KEY'] %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <% if current_store.subscription.trial? %>
    <%= render 'subscriptions/trial' %>
  <% end %>
  <%= render 'shared/flash_notification' %>
  <%= yield %>
  <%= debug(params)if Rails.env.development? %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicShelf</title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/home_navbar' %>
  <%= render 'shared/flash_notification' %>
  <%= yield %>
  <%= debug(params)if Rails.env.development? %>
  <%= "Schema: #{DatabaseUtility.current}" if Rails.env.development? %>
</body>
</html>